"""empty message

Revision ID: f570f0a66eed
Revises: b428afe10460
Create Date: 2022-07-22 16:02:24.534113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f570f0a66eed'
down_revision = 'b428afe10460'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'wallet', ['currency_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.create_foreign_key(None, 'transaction', 'currency', ['currency_id'], ['id'])
    # ### end Alembic commands ###
